language: python
python:
  - "3.6"
matrix:
   os: windows
      language: sh
      python: "3.7"
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python sender.py
  - python replicator.py
