language: python
python:
  - "3.7-dev"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python keeper.py
  - python logger.py
  - python replicator.py
  - python sender.py
  - python executer.py
