# https://ci.appveyor.com/project/PedrV/silverheart
build: false

environment:
  PYTHONIOENCODING: "utf-8"
  matrix:
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python37"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"

test_script:
  - "%PYTHON%/Scripts/pip.exe --version"
  - "%PYTHON%/Scripts/pip.exe freeze"
  - "%PYTHON%/python.exe --version"
  - "%PYTHON%/Scripts/pip.exe install \"importlib-metadata>=0.12\""
  - "%PYTHON%/python.exe setup.py test"
